export const preloadTemplates = async function() {
  
  return loadTemplates({
    actorMainName: CONFIG._root+"/templates/fragments/actor_main_name.html",
    actorMainPortrait: CONFIG._root+"/templates/fragments/actor_main_portrait.html",
    actorMainCharacteristics: CONFIG._root+"/templates/fragments/actor_main_characteristics.html",
    actorMainHitPoints: CONFIG._root+"/templates/fragments/actor_main_hitPoints.html",
    actorMenu: CONFIG._root+"/templates/fragments/actor_menu.html",
    actorActorCharacteristics: CONFIG._root+"/templates/fragments/actor_actor_characteristics.html",
    actorActorOctagon: CONFIG._root+"/templates/fragments/actor_actor_octagon.html",
    actorActorPortrait: CONFIG._root+"/templates/fragments/actor_actor_portrait.html",
    actorActorRationality: CONFIG._root+"/templates/fragments/actor_actor_rationality.html",
    actorActorIrrationality: CONFIG._root+"/templates/fragments/actor_actor_irrationality.html",
    actorActorLore: CONFIG._root+"/templates/fragments/actor_actor_lore.html",
    actorActorTraits: CONFIG._root+"/templates/fragments/actor_actor_traits.html",
    actorActorSequels: CONFIG._root+"/templates/fragments/actor_actor_sequels.html",
    actorSheetActor: CONFIG._root+"/templates/fragments/actor_sheet_actor.html",
    actorSheetCombat: CONFIG._root+"/templates/fragments/actor_sheet_combat.html",
    actorSheetEquipment: CONFIG._root+"/templates/fragments/actor_sheet_equipment.html",
    actorSheetMagic: CONFIG._root+"/templates/fragments/actor_sheet_magic.html",
    actorSheetSkills: CONFIG._root+"/templates/fragments/actor_sheet_skills.html",
    actorModes: CONFIG._root+"/templates/fragments/actor_modes.html",

    actorCombatActionDiag: CONFIG._root+"/templates/fragments/actor_combat_actionDiag.html",
    actorCombatHeader: CONFIG._root+"/templates/fragments/actor_combat_header.html",
    actorCombatCombatBar: CONFIG._root+"/templates/fragments/actor_combat_combatBar.html",
    actorCombatMainFrame: CONFIG._root+"/templates/fragments/actor_combat_mainFrame.html",
    actorCombatMenuFrame: CONFIG._root+"/templates/fragments/actor_combat_menuFrame.html",
    actorCombatStepsBar: CONFIG._root+"/templates/fragments/actor_combat_stepsBar.html",
    actorCombatWeaponDiag: CONFIG._root+"/templates/fragments/actor_combat_weaponDiag.html",
    actorCombatWeaponInfo1: CONFIG._root+"/templates/fragments/actor_combat_weaponDiag_info1.html",
    actorCombatWeaponInfo2: CONFIG._root+"/templates/fragments/actor_combat_weaponDiag_info2.html",

    actorCombatFrameCombat: CONFIG._root+"/templates/fragments/actor_combatFrame_combat.html",
    actorCombatFrameEncounter: CONFIG._root+"/templates/fragments/actor_combatFrame_encounter.html",
    actorCombatFrameCombatant: CONFIG._root+"/templates/fragments/actor_combatFrame_combatant.html",
    actorCombatFrameSummary: CONFIG._root+"/templates/fragments/actor_combatFrame_summary.html",

    actorCombatFrameMyCombat: CONFIG._root+"/templates/fragments/actor_combatFrame_myCombat.html",
    actorCombatFrameMyWeapons: CONFIG._root+"/templates/fragments/actor_combatFrame_myWeapons.html",
    actorCombatFrameMyArmor: CONFIG._root+"/templates/fragments/actor_combatFrame_myArmor.html",
    actorCombatFrameMyActions: CONFIG._root+"/templates/fragments/actor_combatFrame_myActions.html",

    actorCombatFrameTurnFlux: CONFIG._root+"/templates/fragments/actor_combatFrame_turn_flux.html",
    actorCombatFrameTurnAttacker: CONFIG._root+"/templates/fragments/actor_combatFrame_turn_attacker.html",
    actorCombatFrameTurnTarget: CONFIG._root+"/templates/fragments/actor_combatFrame_turn_target.html",
    actorCombatFrameTurnOppoRoll: CONFIG._root+"/templates/fragments/actor_combatFrame_turn_oppoRoll.html",
    actorCombatFrameTurnDamage: CONFIG._root+"/templates/fragments/actor_combatFrame_turn_damage.html",
    actorCombatFrameTurnAttackerWeapon: CONFIG._root+"/templates/fragments/actor_combatFrame_turn_attackWeapon.html",
    actorCombatFrameTurnTargetWeapon: CONFIG._root+"/templates/fragments/actor_combatFrame_turn_targetWeapon.html",
    
    actorEquipmentArmor: CONFIG._root+"/templates/fragments/actor_equipment_armor.html",
    actorEquipmentArmorTree: CONFIG._root+"/templates/fragments/actor_equipment_armorTree.html",
    actorEquipmentEquipment: CONFIG._root+"/templates/fragments/actor_equipment_equipment.html",
    actorEquipmentWeapons: CONFIG._root+"/templates/fragments/actor_equipment_weapons.html",

    actorMagicCells: CONFIG._root+"/templates/fragments/actor_magic_cells.html",
    actorMagicTheo: CONFIG._root+"/templates/fragments/actor_magic_theo.html",
    actorMagicStudy: CONFIG._root+"/templates/fragments/actor_magic_study.html",
    actorMagicStudyTheo: CONFIG._root+"/templates/fragments/actor_magic_studyTheo.html",
    actorMagicThrow: CONFIG._root+"/templates/fragments/actor_magic_throw.html",
    actorMagicThrowTheo: CONFIG._root+"/templates/fragments/actor_magic_throwTheo.html",
    actorListMagic: CONFIG._root+"/templates/fragments/actor_magic_listMagic.html",
    actorMagicBooks: CONFIG._root+"/templates/fragments/actor_magic_books.html",
    actorMagicList: CONFIG._root+"/templates/fragments/actor_magic_list.html",
    actorMagicInfo: CONFIG._root+"/templates/fragments/actor_magic_info.html",
    


    actionDamage: CONFIG._root+"/templates/fragments/action_damage.html",
    actionDescription: CONFIG._root+"/templates/fragments/action_description.html",
    actionFencing: CONFIG._root+"/templates/fragments/action_fencing.html",
    actionMain: CONFIG._root+"/templates/fragments/action_main.html",
    actionModifiers: CONFIG._root+"/templates/fragments/action_modifiers.html",
    actionRoll: CONFIG._root+"/templates/fragments/action_roll.html",
    actionDefense: CONFIG._root+"/templates/fragments/action_defense.html",
    actionWeapons: CONFIG._root+"/templates/fragments/action_weapons.html",
    weaponMain: CONFIG._root+"/templates/fragments/weapon_main.html",
    weaponContext: CONFIG._root+"/templates/fragments/weapon_context.html",
    weaponShields: CONFIG._root+"/templates/fragments/weapon_shields.html",
    weaponDescription: CONFIG._root+"/templates/fragments/weapon_description.html",
    armorMain: CONFIG._root+"/templates/fragments/armor_main.html",
    armorDescription: CONFIG._root+"/templates/fragments/armor_description.html",    
    loreCusto: CONFIG._root+"/templates/loreCusto.html",
    frame: CONFIG._root+"/templates/fragments/frame.html",
    
  });
};