export const preloadTemplates = async function() {
  
  return loadTemplates({
      humanFrame: CONFIG._root+"/templates/fragments/humanFrame.html",
      humanCrest: CONFIG._root+"/templates/fragments/humanCrest.html",
      humanPageMain: CONFIG._root+"/templates/fragments/humanPageMain.html",
      humanPageBio: CONFIG._root+"/templates/fragments/humanPageBio.html",
      humanPageSkills: CONFIG._root+"/templates/fragments/humanPageSkills.html",
      humanPageCombat: CONFIG._root+"/templates/fragments/humanPageCombat.html",
      humanPageActions: CONFIG._root+"/templates/fragments/humanPageActions.html",
      humanPageArmor: CONFIG._root+"/templates/fragments/humanPageArmor.html",
      humanPageItems: CONFIG._root+"/templates/fragments/humanPageItems.html",
      humanPageMagic: CONFIG._root+"/templates/fragments/humanPageMagic.html",
      humanPageMagicTable: CONFIG._root+"/templates/fragments/humanPageMagicTable.html",
      humanPageMagicCodice: CONFIG._root+"/templates/fragments/humanPageMagicCodice.html",
      humanPosterActions: CONFIG._root+"/templates/fragments/humanPosterActions.html",
      humanPosterTargets: CONFIG._root+"/templates/fragments/humanPosterTargets.html",
      humanHeader: CONFIG._root+"/templates/fragments/humanHeader.html",
      humanCharPrimary: CONFIG._root+"/templates/fragments/humanCharPrimary.html",
      humanCharSecondary: CONFIG._root+"/templates/fragments/humanCharSecondary.html",
      humanCharRational: CONFIG._root+"/templates/fragments/humanCharRational.html",
      humanBio: CONFIG._root+"/templates/fragments/humanBio.html",
      humanBioDescription: CONFIG._root+"/templates/fragments/humanBioDescription.html",
      humanBioBackground: CONFIG._root+"/templates/fragments/humanBioBackground.html",
      humanBioTraits: CONFIG._root+"/templates/fragments/humanBioTraits.html",
      humanBioLanguages: CONFIG._root+"/templates/fragments/humanBioLanguages.html",
      humanLanguages: CONFIG._root+"/templates/fragments/humanLanguages.html",
      humanQuickBar: CONFIG._root+"/templates/fragments/humanQuickBar.html",
      humanModesBar: CONFIG._root+"/templates/fragments/humanModesBar.html",
      humanWizard: CONFIG._root+"/templates/fragments/humanWizard.html",
      humanWizardBar: CONFIG._root+"/templates/fragments/humanWizardBar.html",
      humanWizard01: CONFIG._root+"/templates/fragments/humanWizard01.html",
      humanWizard02: CONFIG._root+"/templates/fragments/humanWizard02.html",
      humanWizard03: CONFIG._root+"/templates/fragments/humanWizard03.html",
      humanWizard04: CONFIG._root+"/templates/fragments/humanWizard04.html",
      humanWizard05: CONFIG._root+"/templates/fragments/humanWizard05.html",
      humanWizard06: CONFIG._root+"/templates/fragments/humanWizard06.html",
      humanWizard07: CONFIG._root+"/templates/fragments/humanWizard07.html",
      humanWizard08: CONFIG._root+"/templates/fragments/humanWizard08.html",
      humanWizard09: CONFIG._root+"/templates/fragments/humanWizard09.html",
      humanWizard10: CONFIG._root+"/templates/fragments/humanWizard10.html",

      humanHeaderShrink: CONFIG._root+"/templates/fragments/humanHeaderShrink.html",
      humanMainShrink: CONFIG._root+"/templates/fragments/humanMainShrink.html",
      
      itemFrame: CONFIG._root+"/templates/fragments/itemFrame.html",
      itemDescription: CONFIG._root+"/templates/fragments/itemDescription.html",
      itemExtendCultures: CONFIG._root+"/templates/fragments/itemExtendCultures.html",
      itemExtendLanguages: CONFIG._root+"/templates/fragments/itemExtendLanguages.html",
      itemExtendSkill: CONFIG._root+"/templates/fragments/itemExtendSkill.html",
      itemExtendArmor: CONFIG._root+"/templates/fragments/itemExtendArmor.html",
      itemExtendWeapon: CONFIG._root+"/templates/fragments/itemExtendWeapon.html",
      itemExtendSpell: CONFIG._root+"/templates/fragments/itemExtendSpell.html",
      itemExtendRitual: CONFIG._root+"/templates/fragments/itemExtendRitual.html",
      itemExtendAction: CONFIG._root+"/templates/fragments/itemExtendAction.html",
      itemExtendMode: CONFIG._root+"/templates/fragments/itemExtendMode.html"

  });
};